### ISSUE TITLE
Install PhotonVision on 2 raspberry pi's

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/RobotCasserole2024#14]
https://docs.photonvision.org/en/latest/docs/installation/sw_install/raspberry-pi.html

**Comment by ElliottHicks1125** [comment]
Attempted to flash two sd cards. Both flashes failed according to etcher, but the previously empty sd cards now contain files. So maybe finished? Not really sure how to connect the pi to wifi to test it.

**Comment by gerth2** [comment]
hook up to the software test bench for test
