### ISSUE TITLE
DeLint Drivetrain

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/RobotCasserole2024#18]
The following files have lint errors in them, fix em

Autonomous\commands\drivePathCommand.py:6:0: 
Autonomous\modes\driveOut.py:3:0:
Autonomous\modes\noteThief.py:3:0:
drivetrain\drivetrainControl.py:9:0: 
drivetrain\controlStrategies\holonomicDriveController.py
drivetrain\controlStrategies\trajectory.py:
utils\allianceTransformUtils.py:1

**Comment by AbbyJune** [comment]
Not perfect... good enough for now.
