### ISSUE TITLE
Calibrate Shooter

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/RobotCasserole2024#40]
Set kV and kP to zero.

Set kV to its theoretical value. Crank it up or down until the steady-state actual shooter speed matches the desired speed for both motors.

Increase kP until shooter speed starts oscillating. Then back it off a bit.

Should be good enough.

**Comment by gerth2** [comment]
https://docs.wpilib.org/en/stable/docs/software/advanced-controls/introduction/tuning-flywheel.html

Needs a robot, but you can practice offline! ^^^^

**Comment by AbbyJune** [comment]
Done on practice.
