### ISSUE TITLE
Calibrate swerve drive module absolute encoder offsets and directions

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/RobotCasserole2024#42]
Run the calibration procedure to set up absolute rotation sensor offsets (see code comments)

Make sure to set inversions so rotation directions match the dashboard for all four modules. Note the back two motors were flipped over, so it's likely at least some of those will need some inversion

**Comment by AbbyJune** [comment]
Done on practice bot... waiting on real.
