### ISSUE TITLE
AutoAlign to Amp

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/RobotCasserole2024#44]
![image](https://github.com/RobotCasserole1736/RobotCasserole2024/assets/4583662/4e5c0de7-e1a2-4ca7-84f9-c395e939638e)

THis is currently hardcoded to the speaker position.

Add additional buttons to allow the operator to command auto align to amp. The button should activate auto-align, but pick the amp position rather than the speaker

**Comment by AbbyJune** [comment]
Low priority: Do later. It's the last milestone to hit! And if the driver/operator don't want it, we wont' do it anyways. 

But we wanna do other stuff now.
