### ISSUE TITLE
Support Driver Camera

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/RobotCasserole2024#5]
USB Microsoft lifecam - needs to show up in dashboards and on the website

**Comment by gerth2** [comment]
https://docs.wpilib.org/en/stable/docs/software/vision-processing/introduction/cameraserver-class.html#cameraserver-class - see the `startAutomaticCapture()` method

**Comment by gojira2021** [comment]
Currently the Driver Camera works on the FRC Dashboard.  I can continue to work on it to allow it to run on the website but currently we have a functional camera somewhere.

**Comment by gojira2021** [comment]
I'm gonna consider this issue resolved for the time being.  If it is necessary to have a camera running on our dashboard I will return to it and work out the kinks.
