### ISSUE TITLE
Create ClimberControl

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/RobotCasserole2024#7]

**Comment by gerth2** [comment]
Two high-level modes need to be supported:

1) just repositioning the carriages
2) Actually lifting the robot.

While lifting the robot, and the rachet is not engaged, a constant voltage should be applied to offset the robot weight.

Spike Bridge Relay (https://docs.wpilib.org/en/stable/docs/controls-overviews/control-system-hardware.html) is likely going to get used to control the solenoid which will activate and deactivate the rachet.

**Comment by gerth2** [comment]
https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/wpilibj/Relay.html more spike related

**Comment by gojira2021** [comment]
Me and Elliot Watkins Finished the Climber Code.  May require some fine tuning down the line.
